apiVersion: apps/v1
kind: Deployment
metadata:
  name: wiremock
spec:
  replicas: 1
  selector:
    matchLabels:
      app: wiremock
  template:
    metadata:
      labels:
        app: wiremock
    spec:
      containers:
        - name: wiremock
          image: wiremock/wiremock:3.13.0
          args:
            - "--port=8080"
            - "--verbose"
          ports:
            - containerPort: 8080
          readinessProbe:
            httpGet:
              path: /__admin/health
              port: 8080
            initialDelaySeconds: 3
            periodSeconds: 3
---
apiVersion: v1
kind: Service
metadata:
  name: wiremock
spec:
  selector:
    app: wiremock
  ports:
    - port: 8080
      targetPort: 8080
